name: Salvar dados do formul치rio

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run script
      run: |
        echo "Processando dados do formul치rio..."
        # Seu script para processar os dados e salvar no reposit칩rio
        node process_data.js
    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m 'Adicionando novos dados do formul치rio'
        git push
